/**
 * Prettier config file.
 *
 * Prettier is not aware of this config file's location.
 *
 * @note PLEASE DO NOT EDIT THIS FILE!
 * @note This entire file will be updated automatically.
 * @note Instead of editing here, please review <https://github.com/clevercanyon/skeleton>.
 *
 * @see https://prettier.io/docs/en/configuration.html
 */
/* eslint-env es2021, node */

/**
 * Base config.
 */
const baseConfig = {
	/**
	 * Plugins.
	 *
	 * @note We use a bunch.
	 * @note https://o5p.me/xCUiHS
	 */
	pluginSearchDirs: false,
	plugins: ['prettier-plugin-ini', 'prettier-plugin-properties', '@prettier/plugin-xml', '@prettier/plugin-ruby'],

	/**
	 * Standard options.
	 *
	 * @note We define them all.
	 * @note https://o5p.me/mmdRUm
	 */
	arrowParens: 'always',
	bracketSameLine: false,
	bracketSpacing: true,
	embeddedLanguageFormatting: 'auto',
	endOfLine: 'lf',
	htmlWhitespaceSensitivity: 'css',
	insertPragma: false,
	jsxSingleQuote: true,
	printWidth: 180,
	proseWrap: 'preserve',
	quoteProps: 'preserve',
	requirePragma: false,
	semi: true,
	singleAttributePerLine: false,
	singleQuote: true,
	tabWidth: 4,
	trailingComma: 'all',
	useTabs: true,
	vueIndentScriptAndStyle: true,
};

/**
 * Composition.
 */
module.exports = {
	...baseConfig,
	overrides: [
		{
			/**
			 * Enforce JSON parser.
			 *
			 * @see https://o5p.me/sj8jjz
			 */
			files: ['*.json'],
			options: {
				parser: 'json', // Not `json-stringify`.
			},
		},
		{
			/**
			 * Ruby plugin options.
			 *
			 * @see https://o5p.me/tuKNvU
			 */
			files: ['*.rb'],
			options: {
				parser: 'ruby',
				rubyPlugins: '',
				rubySingleQuote: true,
			},
		},
		{
			/**
			 * XML plugin options.
			 *
			 * @see https://o5p.me/OiLPzn
			 */
			files: ['*.xml'],
			options: {
				parser: 'xml',
				xmlSelfClosingSpace: true,
				xmlWhitespaceSensitivity: 'ignore',
			},
		},
		{
			/**
			 * INI plugin options.
			 *
			 * @see https://o5p.me/1fqazf
			 */
			files: ['*.ini'],
			options: {
				parser: 'ini',
				iniSpaceAroundEquals: true,
			},
		},
		{
			/**
			 * Properties plugin options.
			 *
			 * @see https://o5p.me/IyzRSp
			 */
			files: ['*.properties', '*.env{,.*}'],
			options: {
				parser: 'dot-properties',
				keySeparator: '=',
				escapeNonLatin1: false,
			},
		},
		{
			/**
			 * YAML spec options.
			 *
			 * @see https://o5p.me/jJH2xY
			 */
			files: ['*.yml', '*.yaml'],
			options: {
				tabWidth: 2,
				useTabs: false,
			},
		},
	],
};
