##
# Wrangler configuration.
#
# Wrangler is aware of this config file's location.
#
# @note CUSTOM EDITS ONLY PLEASE!
# @note In the future this file will be updated automatically.
# @note Only `<custom:start.../custom:end>` will be preserved below.
#
# @todo Auto-generate this file from MJS.
##

##
# Platform settings.
##

compatibility_date = "2023-08-15"
send_metrics = false              # Don't share usage.
usage_model = "bundled"           # 10M/mo free + $0.50/M.

##
# Workers.dev configuration.
##

workers_dev = false
env.dev.workers_dev = false

##
# App main entry configuration.
##

main = "./dist/index.js"

##
# Dynamic import configuration.
##

rules = [
  { type = "ESModule", globs = [
    "**/*.js",
    "**/*.jsx",
    "**/*.mjs",
    "**/*.mjsx",
  ], fallthrough = false },

  { type = "CommonJS", globs = [
    "**/*.cjs",
    "**/*.cjsx",
    "**/*.node",
  ], fallthrough = false },

  { type = "Data", globs = [
    "**/*.bin",
  ], fallthrough = false },

  { type = "CompiledWasm", globs = [
    "**/*.wasm",
  ], fallthrough = false },

  { type = "Text", globs = [
    "**/*.md",
    "**/*.txt",
    "**/*.xml",
    "**/*.html",
    "**/*.shtml",
    "**/*.ejs",
    "**/*.json",
  ], fallthrough = false },
]

##
# Custom build configuration.
##

build.cwd = "./"
build.watch_dir = "./src"

build.command = "npx @clevercanyon/madrun build --mode=prod"
env.dev.build.command = "npx @clevercanyon/madrun build --mode=dev"

##
# Worker sites; i.e., bucket configuration.
##

site.bucket = "./dist/assets"
site.exclude = [
  # @todo Should simply be a reflection of `.npmignore`.

  ##
  # Exactly like `.gitignore`.
  ##

  # Locals.

  ".#*",
  ".~*",
  "*.local",

  # Logs.

  "*.log",
  "*.logs",

  # Backups.

  "*~",
  "*.bak",

  # Patches.

  "*.rej",
  "*.orig",
  "*.patch",
  "*.diff",

  # IntelliJ.

  ".idea",

  # Sublime.

  "*.sublime-project",
  "*.sublime-workspace",

  # Netbeans.

  "*.nbproject",

  # VS Code.

  "*.code-search",
  "*.code-workspace",

  # Dist (must exclude).
  # May contain APP_ env vars.

  "dist",

  # Yarn.

  ".yarn",

  # Vendor.

  "vendor",

  # NodeJS.

  "node_modules",

  # JSPM.

  "jspm_packages",

  # Bower.

  "bower_components",

  # Dotenv.

  ".env*",
  ".flaskenv*",

  "!.env.vault",
  "!.env.project",

  # TypeScript.

  "typings",
  ".tscache",
  "*.tsbuildinfo",

  # Vite.

  ".vite",
  ".vitest",

  # Wrangler.

  ".wrangler",
  ".dev.vars",
  ".dev.vars.*",

  # Rollup.

  ".rollup",

  # Webpack.

  ".webpack",

  # Linaria.

  ".linaria-cache",

  # SASS.

  ".sass-cache",

  # Docker.

  ".docker",

  # Vagrant.

  ".vagrant",

  # Elastic Beanstalk.

  ".elasticbeanstalk",

  # CTAGs.

  "*.ctags",
  "*.tags",

  # VCS.

  ".git",

  ".svn",
  "_svn",
  ".svnignore",

  "CVS",
  ".cvsignore",

  ".bzr",
  ".bzrignore",

  ".hg",
  ".hgignore",

  "SCCS",
  "RCS",

  # PC files.

  "Thumbs.db",
  "ehthumbs.db",
  "Desktop.ini",

  # PC directories.

  "$RECYCLE.BIN",

  # Mac files.

  "._*",
  "Icon?",
  "!Icons",
  "*.icloud",
  ".DS_Store",
  ".disk_label",
  ".LSOverride",
  ".VolumeIcon.icns",
  ".com.apple.timemachine.*",

  # Mac directories.

  ".apdisk",
  "*.icloud",
  ".fseventsd",
  ".AppleDB",
  ".AppleDesktop",
  ".AppleDouble",
  ".Trashes",
  ".TemporaryItems",
  ".Spotlight-V100",
  ".DocumentRevisions-V100",
  "Network Trash Folder",
  "Temporary Items",

  ##
  # Exactly like `.npmignore`.
  ##

  # Dist (allow).

  "!dist",

  # Configs.

  "tsconfig.*",
  "*.config.*",
  "wrangler.*",

  # Raw sources.

  "*.scss",
  "!dist/**/*.scss",

  "*.less",
  "!dist/**/*.less",

  "*.ejs",
  "!dist/**/*.ejs",

  "*.jsx",
  "!dist/**/*.jsx",

  "*.ts",
  "!*.d.ts",
  "!dist/**/*.ts",

  "*.tsx",
  "!*.d.tsx",
  "!dist/**/*.tsx",

  "*.cts",
  "!*.d.cts",
  "!dist/**/*.cts",

  "*.ctsx",
  "!*.d.ctsx",
  "!dist/**/*.ctsx",

  "*.mts",
  "!*.d.mts",
  "!dist/**/*.mts",

  "*.mtsx",
  "!*.d.mtsx",
  "!dist/**/*.mtsx",

  # Dots.

  ".*",

  # Src.

  "src",

  # Dev.

  "dev",

  # Sandbox.

  "sandbox",

  # Examples.

  "example",
  "examples",

  # Docs.

  "doc",
  "docs",
  "*.doc.*",
  "*.docs.*",
  "readme.*",
  "*.readme.*",

  # Tests.

  "test",
  "tests",
  "*.test.*",
  "*.tests.*",
  "*.test-d.*",
  "*.tests-d.*",

  # Specs.

  "spec",
  "specs",
  "*.spec.*",
  "*.specs.*",
  "*.spec-d.*",
  "*.specs-d.*",

  # Benchmarks.

  "bench",
  "benchmark",
  "benchmarks",
  "*.bench.*",
  "*.benchmark.*",
  "*.benchmarks.*",

  ##
  # Other exclusions.
  ##

  # A16s (top level).

  "/a16s",
]

##
# Customizations.
# <custom:start>

name = "utilities-node"
route.zone_name = "hop.gdn"
route.pattern = "workers.hop.gdn/utilities-node/*"
account_id = "f1176464a976947aa5665d989814a4b1"

# </custom:end>
